version: "3"
services:
  app:
    image: ghcr.io/ixxvivxxi/beauty-shop/beauty-shop-app:latest
    container_name: beauty-shop-app
    restart: unless-stopped
    links:
      - "db:db"
    volumes:
      - ./db-data:/var/lib/mysql
      - ./images:/opt/app/server/public/images
      - ./.env:/opt/app/server/.env
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    working_dir: /opt/app/server
    ports:
      - 8080:80
    environment:
      TZ: Europe/Minsk
    networks:
      - app-network

  db:
    image: mysql
    container_name: beauty-shop-db
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: Europe/Minsk
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./db-data:/var/lib/mysql
    networks:
      - app-network
      
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: ${DB_PORT}
      UPLOAD_LIMIT: 500M
    ports:
      - 9000:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
